spring:
  application:
    name: Identity-Service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/avanza_natural
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
server:
  port: 9090
web:
  service:
    uri: http://localhost:3000
jwt:
  secret: 5367566B5970337336762342342342341139792F4123F452811482B4D6251655468576D5A71347437